config/routes.rb
Air::Application.routes.draw do

get "sessions/new"
post "session/create"
get "session/destroy"

  resources :users

  get "flights/index" => 'flights#index'

   root to: 'flights#index'

   get '/mockup' => 'pages#home'
   get '/help' => 'pages#help', :as => :help
  
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrival_airport_code, :departs_at, :departure_airport_code, :distance, :number
  
  def bookable?
    seats_remaining > 0
  end
  
  def arrives_at
    minutes = distance.to_f / 8
    return self.departs_at + (minutes * 60)
  end
  
end

app/models/mileage_calculator.rb
class MileageCalculator
  
  #   codes = ['ORD', 'JFK', 'BOS', 'LAX']
  
  CHART = { "ORD-JFK" => 740, 
            'ORD-BOS' => 866, 
            'ORD-LAX' => 1744, 
            'JFK-BOS' => 186, 
            'JFK-LAX' => 2475,  
            'BOS-LAX' => 2611 
          }
  
  def initialize(departure_airport_code, arrival_airport_code)
    @departure_airport_code = departure_airport_code
    @arrival_airport_code = arrival_airport_code
  end
  
  def miles
    
  end
  
  def duration
    
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
  
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
 
  def index
    @flights = Flight.all
  
    @user = User.find_by_id(session["zebra"])
  end
end

  

  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flights/index.html.erb
<%= notice %>

<% if @user.present? %>
<%= @user.email %>
<% end %>

<h2>Daily Flight Schedule</h2>

<div id="search">
	<label for="keyword">Search:</label><input type="text" name="keyword" placeholder="Enter an Airport Code" size="30">
</div>

<table>
  <thead>
    <tr>
      <th>
      <th>Flight Number</th>
      <th>Leaves</th>
      <th>Time</th>
      <th>Arrives</th>
      <th>Time</th>
      <th>Seats Remaining</th>
      <th>Miles</th>
    </tr>
  </thead>
  <tbody>
<%= @flights.each do |flight| %>
    <tr>
      <td><% if flight.bookable? %><button>Book Now</button></td>
      <td><%= flight.number %></td>
      <td><%= flight.number_airport_code %></td>
      <td><%= flight.departs_at.localtime.strftime("%l:%M %P") %></td>
      <td>flight.arrival_airport_code</td>
      <td><%= flight.arrives_at.localtime.strftime("%l:%M %P") %></td>
      <td><%= flights.seats_remaining %></td>
      <td>flight.distance</td>
    </tr>
    <tr>
      <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Academy Air</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="container">
		<header>
			<h1><%= link_to "Academy Air", root_url %></h1>
			<nav>
				<ul>
					<li><%= link_to "View My Profile", '#' %></li>
					<li><%= link_to "Help", help_url %></li>
					<li><%= link_to "Sign Out", '#' %></li>
				</ul>
			</nav>
			<p>Hello, Bob!</p>
		</header>

		<div id="content">
			<%= yield %>
		</div>
		
		<footer>
			&copy;2012 Academy Air, Inc.  Got comments or suggestions? Keep 'em to yourself!
		</footer>
	</div>
</body>
</html>

app/views/pages/help.html.erb
<div id="help">

<p><strong>MVP User Stories</strong></p>

<ol>
  <li>As a visitor, I want to see the list of flights that are available each day.
      <span><br/>TIP: You can display 0 for the mileage and duration for now.  Later we will use the MileageCalculator class to calculate those as needed.</span></li>
  <li>As a visitor, I want to create a user account, so that I can make reservations.</li>
  <li>As a user, I want to see a profile page that shows how many frequent flyer miles I’ve earned.</li>
  <li>As a user, I want to make a reservation.</li>
  <li>As a user, I expect my frequent flyer mileage total to increase every time I reserve a flight.</li>
  <li>As a user, I want to see my reservations in my account profile.</li>
  <li>As a user, I want to search for flights by airport code.</li>
  <li>As a user, I want to search for flights by airport code or city name.</li>
  <li>As a user, I want to first see my account profile when I login.</li>
  <li>As a user, I want to receive an email confirming my reservation.</li>
</ol>

<p id="ground_rules"><strong>Ground Rules (get it?)</strong></p>
<ol>
  <li>Planes fly at about 8 miles per minute, so the arrival time and flight duration could, in theory, be calculated rather than stored in the database.</li>
  <li>Every Academy Air flight costs the same: $70.</li>
  <li>We only accept Visa credit cards.  Visa cards are 16-digits numbers that always start with the number 4.</li>
</ol>


</div>

app/views/pages/home.html.erb
<h2>Daily Flight Schedule</h2>

<div id="search">
	<label for="keyword">Search:</label><input type="text" name="keyword" placeholder="Enter an Airport Code" size="30">
</div>

<table>
  <thead>
    <tr>
      <th>
      <th>Flight Number</th>
      <th>Leaves</th>
      <th>Time</th>
      <th>Arrives</th>
      <th>Time</th>
      <th>Seats Remaining</th>
      <th>Miles</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><button>Book Now</button></td>
      <td>104</td>
      <td>ORD</td>
      <td>10:00 am</td>
      <td>BOS</td>
      <td>1:00 pm</td>
      <td>60</td>
      <td>1846</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>216</td>
      <td>JFK</td>
      <td>9:34 am</td>
      <td>LAX</td>
      <td>12:46 pm</td>
      <td>8</td>
      <td>2475</td>
    </tr>
    <tr>
      <td></td>
      <td>908</td>
      <td>ORD</td>
      <td>10:41 am</td>
      <td>BOS</td>
      <td>1:31 pm</td>
      <td>0</td>
      <td>866</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>761</td>
      <td>JFK</td>
      <td>10:00 am</td>
      <td>BOS</td>
      <td>1:00 pm</td>
      <td>42</td>
      <td>186</td>
    </tr>    
    <tr>
      <td><button>Book Now</button></td>
      <td>104</td>
      <td>BOS</td>
      <td>3:12 pm</td>
      <td>ORD</td>
      <td>5:18pm</td>
      <td>60</td>
      <td>1846</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>216</td>
      <td>LAX</td>
      <td>11:25 am</td>
      <td>JFK</td>
      <td>1:00 pm</td>
      <td>8</td>
      <td>2475</td>
    </tr>
    <tr>
      <td></td>
      <td>908</td>
      <td>LAX</td>
      <td>8:00 am</td>
      <td>ORD</td>
      <td>1:00 pm</td>
      <td>0</td>
      <td>866</td>
    </tr>
    <tr>
      <td><button>Book Now</button></td>
      <td>761</td>
      <td>BOS</td>
      <td>2:00 pm</td>
      <td>JFK</td>
      <td>4:00 pm</td>
      <td>42</td>
      <td>186</td>
    </tr>
    
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>